TUNE=base
LABEL=ycl-64
NUMBER=505
NAME=mcf_r
SOURCES= mcf.c mcfutil.c readmin.c implicit.c pstart.c output.c treeup.c \
	 pbla.c pflowup.c psimplex.c pbeampp.c spec_qsort/spec_qsort.c
EXEBASE=mcf_r
NEED_MATH=yes
BENCHLANG=C

BENCH_CFLAGS     = -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP
CC               = $(SPECLANG)gcc     -std=c99   
CC_VERSION_OPTION = --version
CXX              = $(SPECLANG)g++     -std=c++03 
CXX_VERSION_OPTION = --version
EXTRA_CFLAGS     = -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon
EXTRA_PORTABILITY = -DSPEC_LP64
FC               = $(SPECLANG)gfortran           
FC_VERSION_OPTION = --version
OPTIMIZE         = -march=native -DENABLE_FP -Ofast -fomit-frame-pointer -flto
OS               = unix
SPECLANG         = /usr/bin/
absolutely_no_locking = 0
abstol           = 
action           = validate
allow_label_override = 0
backup_config    = 1
baseexe          = mcf_r
basepeak         = 0
benchdir         = benchspec
benchmark        = 505.mcf_r
binary           = 
bindir           = exe
builddir         = build
bundleaction     = 
bundlename       = 
calctol          = 1
changedhash      = 0
check_version    = 0
clean_between_builds = no
command_add_redirect = 1
commanderrfile   = speccmds.err
commandexe       = mcf_r_base.ycl-64
commandfile      = speccmds.cmd
commandoutfile   = speccmds.out
commandstdoutfile = speccmds.stdout
comparedir       = compare
compareerrfile   = compare.err
comparefile      = compare.cmd
compareoutfile   = compare.out
comparestdoutfile = compare.stdout
compile_error    = 0
compwhite        = 
configdir        = config
configfile       = ycl
configpath       = /home/yangchunlin/cpu2017-64KB/config/ycl.cfg
copies           = 24
current_range    = 
datadir          = data
default_size     = ref
default_submit   = $command
delay            = 0
deletebinaries   = 0
deletework       = 0
dependent_workloads = 0
device           = 
difflines        = 10
dirprot          = 511
discard_power_samples = 0
enable_monitor   = 1
endian           = 12345678
env_vars         = 0
expand_notes     = 0
expid            = 
exthash_bits     = 256
failflags        = 0
fake             = 0
feedback         = 1
flag_url_base    = https://www.spec.org/auto/cpu2017/Docs/benchmarks/flags/
floatcompare     = 
force_monitor    = 0
from_runcpu      = 2
fw_bios          = 
hostname         = localhost.localdomain
http_proxy       = 
http_timeout     = 30
hw_avail         = 
hw_cpu_max_mhz   = 3000
hw_cpu_name      = Neoverse-N1
hw_cpu_nominal_mhz = 3000
hw_disk          = 3.6 TB  add more disk info here
hw_memory001     = 126.085 GB fixme: If using DDR4, the format is:
hw_memory002     = 'N GB (N x N GB nRxn PC4-nnnnX-X)'
hw_model         = 
hw_nchips        = 1
hw_ncores        = 8
hw_ncpuorder     = 
hw_nthreadspercore = 1
hw_ocache        = 
hw_other         = 
hw_pcache        = 
hw_scache        = 
hw_tcache        = 
hw_vendor        = My Corporation
idle_current_range = 
idledelay        = 10
idleduration     = 60
ignore_errors    = 1
ignore_sigint    = 0
ignorecase       = 
info_wrap_columns = 50
inputdir         = input
inputgenerrfile  = inputgen.err
inputgenfile     = inputgen.cmd
inputgenoutfile  = inputgen.out
inputgenstdoutfile = inputgen.stdout
iteration        = -1
iterations       = 1
keeptmp          = 0
label            = ycl-64
license_num      = nnn (Your SPEC license number)
line_width       = 1020
link_input_files = 1
locking          = 1
log              = CPU2017
log_line_width   = 1020
log_timestamp    = 0
logfile          = /home/yangchunlin/cpu2017-64KB/tmp/CPU2017.001/templogs/preenv.intrate.001.0.log
logname          = /home/yangchunlin/cpu2017-64KB/tmp/CPU2017.001/templogs/preenv.intrate.001.0.log
lognum           = 001.0
mail_reports     = all
mailcompress     = 0
mailmethod       = smtp
mailport         = 25
mailserver       = 127.0.0.1
mailto           = 
make             = specmake
make_no_clobber  = 0
makefile_template = Makefile.YYYtArGeTYYYspec
makeflags        = --jobs=8
max_average_uncertainty = 1
max_hum_limit    = 0
max_report_runs  = 3
max_unknown_uncertainty = 1
mean_anyway      = 1
meter_connect_timeout = 30
meter_errors_default = 5
meter_errors_percentage = 5
min_report_runs  = 2
min_temp_limit   = 20
minimize_builddirs = 0
minimize_rundirs = 0
name             = mcf_r
nansupport       = 
need_math        = yes
no_input_handler = close
no_monitor       = 
noratios         = 0
note_preenv      = 1
notes_plat_sysinfo_100 = 
notes_plat_sysinfo_101 =  Sysinfo program /home/yangchunlin/cpu2017-64KB/bin/sysinfo
notes_plat_sysinfo_102 =  Rev: r6732 of 2022-11-07 fe91c89b7ed5c36ae2c92cc097bec197
notes_plat_sysinfo_103 =  running on localhost.localdomain Thu Jan 29 18:32:27 2026
notes_plat_sysinfo_104 = 
notes_plat_sysinfo_105 =  SUT (System Under Test) info as seen by some common utilities.
notes_plat_sysinfo_107 = 
notes_plat_sysinfo_108 =  ------------------------------------------------------------
notes_plat_sysinfo_109 =  Table of contents
notes_plat_sysinfo_110 =  ------------------------------------------------------------
notes_plat_sysinfo_111 =   1. uname -a
notes_plat_sysinfo_112 =   2. w
notes_plat_sysinfo_113 =   3. Username
notes_plat_sysinfo_114 =   4. ulimit -a
notes_plat_sysinfo_115 =   5. sysinfo process ancestry
notes_plat_sysinfo_116 =   6. /proc/cpuinfo
notes_plat_sysinfo_117 =   7. lscpu
notes_plat_sysinfo_118 =   8. numactl --hardware
notes_plat_sysinfo_119 =   9. /proc/meminfo
notes_plat_sysinfo_120 =  10. who -r
notes_plat_sysinfo_121 =  11. Systemd service manager version: systemd 255 (v255-34.oe2403sp1)
notes_plat_sysinfo_122 =  12. Failed units, from systemctl list-units --state=failed
notes_plat_sysinfo_123 =  13. Services, from systemctl list-unit-files
notes_plat_sysinfo_124 =  14. Linux kernel boot-time arguments, from /proc/cmdline
notes_plat_sysinfo_125 =  15. cpupower frequency-info
notes_plat_sysinfo_126 =  16. tuned-adm active
notes_plat_sysinfo_127 =  17. sysctl
notes_plat_sysinfo_128 =  18. /sys/kernel/mm/transparent_hugepage
notes_plat_sysinfo_129 =  19. /sys/kernel/mm/transparent_hugepage/khugepaged
notes_plat_sysinfo_130 =  20. OS release
notes_plat_sysinfo_131 =  21. Disk information
notes_plat_sysinfo_132 =  22. /sys/devices/virtual/dmi/id
notes_plat_sysinfo_133 =  23. dmidecode
notes_plat_sysinfo_134 =  24. BIOS
notes_plat_sysinfo_135 =  ------------------------------------------------------------
notes_plat_sysinfo_206 = 
notes_plat_sysinfo_207 =  ------------------------------------------------------------
notes_plat_sysinfo_208 =  1. uname -a
notes_plat_sysinfo_209 =    Linux localhost.localdomain 6.6.0 \#3 SMP Wed Jan 28 15:30:18 CST 2026 aarch64 aarch64 aarch64 GNU/Linux
notes_plat_sysinfo_210 = 
notes_plat_sysinfo_211 =  ------------------------------------------------------------
notes_plat_sysinfo_212 =  2. w
notes_plat_sysinfo_213 =     18:32:27 up 2 min,  6 users,  load average: 0.33, 0.19, 0.08
notes_plat_sysinfo_214 =    USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
notes_plat_sysinfo_215 =    root     pts/0     18:30    2:09   0.02s  0.02s -bash
notes_plat_sysinfo_216 =    root     pts/1     18:30    2:09   0.02s  0.02s -bash
notes_plat_sysinfo_217 =    root     pts/2     18:30    2:09   0.02s  0.02s -bash
notes_plat_sysinfo_218 =    root     pts/3     18:30    3.00s  1.29s   ?    sh -c w 2>/dev/null
notes_plat_sysinfo_219 =    root     pts/4     18:30    1:43   0.02s  0.02s -bash
notes_plat_sysinfo_220 =    root     pts/5     18:31   11.00s  0.04s  0.04s -bash
notes_plat_sysinfo_221 = 
notes_plat_sysinfo_222 =  ------------------------------------------------------------
notes_plat_sysinfo_223 =  3. Username
notes_plat_sysinfo_224 =    From environment variable $USER:  root
notes_plat_sysinfo_225 = 
notes_plat_sysinfo_226 =  ------------------------------------------------------------
notes_plat_sysinfo_227 =  4. ulimit -a
notes_plat_sysinfo_228 =    real-time non-blocking time  (microseconds, -R) unlimited
notes_plat_sysinfo_229 =    core file size              (blocks, -c) unlimited
notes_plat_sysinfo_230 =    data seg size               (kbytes, -d) unlimited
notes_plat_sysinfo_231 =    scheduling priority                 (-e) 0
notes_plat_sysinfo_232 =    file size                   (blocks, -f) unlimited
notes_plat_sysinfo_233 =    pending signals                     (-i) 129076
notes_plat_sysinfo_234 =    max locked memory           (kbytes, -l) unlimited
notes_plat_sysinfo_235 =    max memory size             (kbytes, -m) unlimited
notes_plat_sysinfo_236 =    open files                          (-n) 1024
notes_plat_sysinfo_237 =    pipe size                (512 bytes, -p) 8
notes_plat_sysinfo_238 =    POSIX message queues         (bytes, -q) 819200
notes_plat_sysinfo_239 =    real-time priority                  (-r) 0
notes_plat_sysinfo_240 =    stack size                  (kbytes, -s) 8192
notes_plat_sysinfo_241 =    cpu time                   (seconds, -t) unlimited
notes_plat_sysinfo_242 =    max user processes                  (-u) 129076
notes_plat_sysinfo_243 =    virtual memory              (kbytes, -v) unlimited
notes_plat_sysinfo_244 =    file locks                          (-x) unlimited
notes_plat_sysinfo_245 = 
notes_plat_sysinfo_246 =  ------------------------------------------------------------
notes_plat_sysinfo_247 =  5. sysinfo process ancestry
notes_plat_sysinfo_248 =   /usr/lib/systemd/systemd --switched-root --system --deserialize=34 rhgb
notes_plat_sysinfo_249 =   sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
notes_plat_sysinfo_250 =   sshd: root [priv]
notes_plat_sysinfo_251 =   sshd: root@pts/0,pts/1,pts/2,pts/3,pts/4
notes_plat_sysinfo_252 =   -bash
notes_plat_sysinfo_253 =   runcpu --config=ycl --size=refrate --copies=24 --noreportable --tune=base --iterations=1 intrate
notes_plat_sysinfo_254 =   runcpu --configfile ycl --size refrate --copies 24 --noreportable --tune base --iterations 1 --noreportable
notes_plat_sysinfo_255 =     --nopower --runmode rate --tune base --size refrate intrate --nopreenv --note-preenv --logfile
notes_plat_sysinfo_256 =     $SPEC/tmp/CPU2017.001/templogs/preenv.intrate.001.0.log --lognum 001.0 --from_runcpu 2
notes_plat_sysinfo_257 =   specperl $SPEC/bin/sysinfo
notes_plat_sysinfo_258 =  $SPEC = /home/yangchunlin/cpu2017-64KB
notes_plat_sysinfo_259 = 
notes_plat_sysinfo_260 =  ------------------------------------------------------------
notes_plat_sysinfo_261 =  6. /proc/cpuinfo
notes_plat_sysinfo_262 =      CPU implementer : 0x41
notes_plat_sysinfo_263 =      CPU architecture: 8
notes_plat_sysinfo_264 =      CPU variant     : 0x3
notes_plat_sysinfo_265 =      CPU part        : 0xd0c
notes_plat_sysinfo_266 =      CPU revision    : 1
notes_plat_sysinfo_267 =      Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc
notes_plat_sysinfo_268 =                        dcpop asimddp
notes_plat_sysinfo_269 = 
notes_plat_sysinfo_270 =  ------------------------------------------------------------
notes_plat_sysinfo_271 =  7. lscpu
notes_plat_sysinfo_272 = 
notes_plat_sysinfo_273 =  From lscpu from util-linux 2.39.1:
notes_plat_sysinfo_274 =    Architecture:                         aarch64
notes_plat_sysinfo_275 =    CPU op-mode(s):                       32-bit, 64-bit
notes_plat_sysinfo_276 =    Byte Order:                           Little Endian
notes_plat_sysinfo_277 =    CPU(s):                               64
notes_plat_sysinfo_278 =    On-line CPU(s) list:                  0-63
notes_plat_sysinfo_279 =    Vendor ID:                            ARM
notes_plat_sysinfo_280 =    BIOS Vendor ID:                       Ampere(R)
notes_plat_sysinfo_281 =    Model name:                           Neoverse-N1
notes_plat_sysinfo_282 =    BIOS Model name:                      Ampere(R) Altra(R) Processor Q64-30 3.00GHz Q64-30 CPU @ 3.0GHz
notes_plat_sysinfo_283 =    BIOS CPU family:                      257
notes_plat_sysinfo_284 =    Model:                                1
notes_plat_sysinfo_285 =    Thread(s) per core:                   1
notes_plat_sysinfo_286 =    Core(s) per socket:                   64
notes_plat_sysinfo_287 =    Socket(s):                            1
notes_plat_sysinfo_288 =    Stepping:                             r3p1
notes_plat_sysinfo_289 =    Frequency boost:                      disabled
notes_plat_sysinfo_290 =    CPU(s) scaling MHz:                   100%
notes_plat_sysinfo_291 =    CPU max MHz:                          3000.0000
notes_plat_sysinfo_292 =    CPU min MHz:                          1000.0000
notes_plat_sysinfo_293 =    BogoMIPS:                             50.00
notes_plat_sysinfo_294 =    Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid
notes_plat_sysinfo_295 =                                          asimdrdm lrcpc dcpop asimddp
notes_plat_sysinfo_296 =    L1d cache:                            4 MiB (64 instances)
notes_plat_sysinfo_297 =    L1i cache:                            4 MiB (64 instances)
notes_plat_sysinfo_298 =    L2 cache:                             64 MiB (64 instances)
notes_plat_sysinfo_299 =    NUMA node(s):                         1
notes_plat_sysinfo_300 =    NUMA node0 CPU(s):                    0-63
notes_plat_sysinfo_301 =    Vulnerability Gather data sampling:   Not affected
notes_plat_sysinfo_302 =    Vulnerability Itlb multihit:          Not affected
notes_plat_sysinfo_303 =    Vulnerability L1tf:                   Not affected
notes_plat_sysinfo_304 =    Vulnerability Mds:                    Not affected
notes_plat_sysinfo_305 =    Vulnerability Meltdown:               Not affected
notes_plat_sysinfo_306 =    Vulnerability Mmio stale data:        Not affected
notes_plat_sysinfo_307 =    Vulnerability Reg file data sampling: Not affected
notes_plat_sysinfo_308 =    Vulnerability Retbleed:               Not affected
notes_plat_sysinfo_309 =    Vulnerability Spec rstack overflow:   Not affected
notes_plat_sysinfo_310 =    Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
notes_plat_sysinfo_311 =    Vulnerability Spectre v1:             Mitigation; __user pointer sanitization
notes_plat_sysinfo_312 =    Vulnerability Spectre v2:             Vulnerable: Unprivileged eBPF enabled
notes_plat_sysinfo_313 =    Vulnerability Srbds:                  Not affected
notes_plat_sysinfo_314 =    Vulnerability Tsx async abort:        Not affected
notes_plat_sysinfo_315 = 
notes_plat_sysinfo_316 =  From lscpu --cache:
notes_plat_sysinfo_317 =       NAME ONE-SIZE ALL-SIZE WAYS TYPE        LEVEL SETS PHY-LINE COHERENCY-SIZE
notes_plat_sysinfo_318 =       L1d       64K       4M    4 Data            1  256                      64
notes_plat_sysinfo_319 =       L1i       64K       4M    4 Instruction     1  256                      64
notes_plat_sysinfo_320 =       L2         1M      64M    8 Unified         2 2048                      64
notes_plat_sysinfo_321 = 
notes_plat_sysinfo_322 =  ------------------------------------------------------------
notes_plat_sysinfo_323 =  8. numactl --hardware
notes_plat_sysinfo_324 =  NOTE: a numactl 'node' might or might not correspond to a physical chip.
notes_plat_sysinfo_325 =    available: 1 nodes (0)
notes_plat_sysinfo_326 =    node 0 cpus: 0-63
notes_plat_sysinfo_327 =    node 0 size: 129110 MB
notes_plat_sysinfo_328 =    node 0 free: 122483 MB
notes_plat_sysinfo_329 =    node distances:
notes_plat_sysinfo_330 =    node   0
notes_plat_sysinfo_331 =      0:  10
notes_plat_sysinfo_332 = 
notes_plat_sysinfo_333 =  ------------------------------------------------------------
notes_plat_sysinfo_334 =  9. /proc/meminfo
notes_plat_sysinfo_335 =     MemTotal:       132209280 kB
notes_plat_sysinfo_336 = 
notes_plat_sysinfo_337 =  ------------------------------------------------------------
notes_plat_sysinfo_338 =  10. who -r
notes_plat_sysinfo_339 =    run-level 3 Jan 29 18:30
notes_plat_sysinfo_340 = 
notes_plat_sysinfo_341 =  ------------------------------------------------------------
notes_plat_sysinfo_342 =  11. Systemd service manager version: systemd 255 (v255-34.oe2403sp1)
notes_plat_sysinfo_343 =    Default Target  Status
notes_plat_sysinfo_344 =    multi-user      degraded
notes_plat_sysinfo_345 = 
notes_plat_sysinfo_346 =  ------------------------------------------------------------
notes_plat_sysinfo_347 =  12. Failed units, from systemctl list-units --state=failed
notes_plat_sysinfo_348 =      UNIT                  LOAD   ACTIVE SUB    DESCRIPTION
notes_plat_sysinfo_349 =    * openibd.service       loaded failed failed openibd - configure Mellanox devices
notes_plat_sysinfo_350 =    * pmlogger.service      loaded failed failed Performance Metrics Archive Logger
notes_plat_sysinfo_351 =    * pmlogger_farm.service loaded failed failed pmlogger farm service
notes_plat_sysinfo_352 =    Legend: LOAD   -> Reflects whether the unit definition was properly loaded.
notes_plat_sysinfo_353 =            ACTIVE -> The high-level unit activation state, i.e. generalization of SUB.
notes_plat_sysinfo_354 =            SUB    -> The low-level unit activation state, values depend on unit type.
notes_plat_sysinfo_355 =    3 loaded units listed.
notes_plat_sysinfo_356 = 
notes_plat_sysinfo_357 =  ------------------------------------------------------------
notes_plat_sysinfo_358 =  13. Services, from systemctl list-unit-files
notes_plat_sysinfo_359 =    STATE            UNIT FILES
notes_plat_sysinfo_360 =    enabled          NetworkManager NetworkManager-dispatcher NetworkManager-wait-online atd auditd chronyd
notes_plat_sysinfo_361 =                     crond docker firewalld getty@ irqbalance iscsi kdump libstoragemgmt libvirtd lm_sensors
notes_plat_sysinfo_362 =                     lvm2-monitor mdmonitor nmb openibd pmcd pmie pmlogger rasdaemon restorecond rngd rpcbind
notes_plat_sysinfo_363 =                     rsyslog smartd smb sshd sysstat systemd-network-generator systemtap tuned udisks2
notes_plat_sysinfo_364 =    enabled-runtime  systemd-fsck-root systemd-remount-fs
notes_plat_sysinfo_365 =    disabled         arp-ethers blk-availability cgdcbxd chrony-wait cni-dhcp console-getty cpupower
notes_plat_sysinfo_366 =                     debug-shell dhcpd dhcpd6 dhcrelay dnsmasq e2scrub_reap ebtables fancontrol fcoe fsidd
notes_plat_sysinfo_367 =                     gssproxy httpd httpd@ hwclock-save ibacm import-state ip6tables ipmievd iprdump iprinit
notes_plat_sysinfo_368 =                     iprupdate ipsec ipset iptables iscsid isnsd kadmin kpatch kprop krb5kdc libvirt-guests
notes_plat_sysinfo_369 =                     lldpad loadmodules lvm2-lvmdbusd multipathd ndctl-monitor nfs-blkmap nfs-server nftables
notes_plat_sysinfo_370 =                     nis-domainname numad nvmefc-boot-connections nvmf-autoconnect openEuler-security opengauss
notes_plat_sysinfo_371 =                     opensmd opensmd@ pcp-geolocate pesign pmfind pmie_farm pmlogger_farm pmproxy postfix
notes_plat_sysinfo_372 =                     powertop psacct quota_nld radiusd ras-mc-ctl rpc-rquotad rrdcached rshim rsyncd sanlock
notes_plat_sysinfo_373 =                     saslauthd selinux-autorelabel-mark snmpd snmptrapd srp_daemon srp_daemon_port@
notes_plat_sysinfo_374 =                     ssh-host-keys-migration sshd-keygen@ systemd-boot-check-no-failures tcsd tog-pegasus
notes_plat_sysinfo_375 =                     virtinterfaced virtlockd virtlogd virtnetworkd virtnodedevd virtnwfilterd virtproxyd
notes_plat_sysinfo_376 =                     virtqemud virtsecretd virtstoraged vsftpd wdmd
notes_plat_sysinfo_377 =    generated        mst
notes_plat_sysinfo_378 =    indirect         pcscd serial-getty@ vsftpd@
notes_plat_sysinfo_379 =    masked           timedatex
notes_plat_sysinfo_380 = 
notes_plat_sysinfo_381 =  ------------------------------------------------------------
notes_plat_sysinfo_382 =  14. Linux kernel boot-time arguments, from /proc/cmdline
notes_plat_sysinfo_383 =    BOOT_IMAGE=/vmlinuz-6.6.0
notes_plat_sysinfo_384 =    root=/dev/mapper/os-root
notes_plat_sysinfo_385 =    ro
notes_plat_sysinfo_386 =    rd.lvm.lv=os/root
notes_plat_sysinfo_387 =    video=VGA-1:640x480-32@60me
notes_plat_sysinfo_388 =    cgroup_disable=files
notes_plat_sysinfo_389 =    apparmor=0
notes_plat_sysinfo_390 =    crashkernel=1024M,high
notes_plat_sysinfo_391 =    smmu.bypassdev=0x1000:0x17
notes_plat_sysinfo_392 =    smmu.bypassdev=0x1000:0x15
notes_plat_sysinfo_393 =    arm64.nopauth
notes_plat_sysinfo_394 =    rhgb
notes_plat_sysinfo_395 =    quiet
notes_plat_sysinfo_396 =    console=tty0
notes_plat_sysinfo_397 = 
notes_plat_sysinfo_398 =  ------------------------------------------------------------
notes_plat_sysinfo_399 =  15. cpupower frequency-info
notes_plat_sysinfo_400 =    analyzing CPU 58:
notes_plat_sysinfo_401 =      current policy: frequency should be within 1000 MHz and 3.00 GHz.
notes_plat_sysinfo_402 =                      The governor "performance" may decide which speed to use
notes_plat_sysinfo_403 =                      within this range.
notes_plat_sysinfo_404 = 
notes_plat_sysinfo_405 =  ------------------------------------------------------------
notes_plat_sysinfo_406 =  16. tuned-adm active
notes_plat_sysinfo_407 =    Current active profile: throughput-performance
notes_plat_sysinfo_408 = 
notes_plat_sysinfo_409 =  ------------------------------------------------------------
notes_plat_sysinfo_410 =  17. sysctl
notes_plat_sysinfo_411 =    kernel.numa_balancing               0
notes_plat_sysinfo_412 =    kernel.randomize_va_space           2
notes_plat_sysinfo_413 =    vm.compaction_proactiveness        20
notes_plat_sysinfo_414 =    vm.dirty_background_bytes           0
notes_plat_sysinfo_415 =    vm.dirty_background_ratio          10
notes_plat_sysinfo_416 =    vm.dirty_bytes                      0
notes_plat_sysinfo_417 =    vm.dirty_expire_centisecs        3000
notes_plat_sysinfo_418 =    vm.dirty_ratio                     60
notes_plat_sysinfo_419 =    vm.dirty_writeback_centisecs      500
notes_plat_sysinfo_420 =    vm.dirtytime_expire_seconds     43200
notes_plat_sysinfo_421 =    vm.extfrag_threshold              500
notes_plat_sysinfo_422 =    vm.min_unmapped_ratio               1
notes_plat_sysinfo_423 =    vm.nr_hugepages                     0
notes_plat_sysinfo_424 =    vm.nr_hugepages_mempolicy           0
notes_plat_sysinfo_425 =    vm.nr_overcommit_hugepages          0
notes_plat_sysinfo_426 =    vm.swappiness                      10
notes_plat_sysinfo_427 =    vm.watermark_boost_factor       15000
notes_plat_sysinfo_428 =    vm.watermark_scale_factor          10
notes_plat_sysinfo_429 =    vm.zone_reclaim_mode                0
notes_plat_sysinfo_430 = 
notes_plat_sysinfo_431 =  ------------------------------------------------------------
notes_plat_sysinfo_432 =  18. /sys/kernel/mm/transparent_hugepage
notes_plat_sysinfo_433 =    defrag          always defer defer+madvise [madvise] never
notes_plat_sysinfo_434 =    enabled         [always] madvise never
notes_plat_sysinfo_435 =    hpage_pmd_size  536870912
notes_plat_sysinfo_436 =    shmem_enabled   always within_size advise [never] deny force
notes_plat_sysinfo_437 = 
notes_plat_sysinfo_438 =  ------------------------------------------------------------
notes_plat_sysinfo_439 =  19. /sys/kernel/mm/transparent_hugepage/khugepaged
notes_plat_sysinfo_440 =    alloc_sleep_millisecs   60000
notes_plat_sysinfo_441 =    defrag                      1
notes_plat_sysinfo_442 =    max_ptes_none            8191
notes_plat_sysinfo_443 =    max_ptes_shared          4096
notes_plat_sysinfo_444 =    max_ptes_swap            1024
notes_plat_sysinfo_445 =    pages_to_scan           65536
notes_plat_sysinfo_446 =    scan_sleep_millisecs    10000
notes_plat_sysinfo_447 = 
notes_plat_sysinfo_448 =  ------------------------------------------------------------
notes_plat_sysinfo_449 =  20. OS release
notes_plat_sysinfo_450 =    From /etc/*-release /etc/*-version
notes_plat_sysinfo_451 =    os-release        openEuler 24.03 (LTS-SP1)
notes_plat_sysinfo_452 =    openEuler-release openEuler release 24.03 (LTS-SP1)
notes_plat_sysinfo_453 =    system-release    openEuler release 24.03 (LTS-SP1)
notes_plat_sysinfo_454 = 
notes_plat_sysinfo_455 =  ------------------------------------------------------------
notes_plat_sysinfo_456 =  21. Disk information
notes_plat_sysinfo_457 =  SPEC is set to: /home/yangchunlin/cpu2017-64KB
notes_plat_sysinfo_458 =    Filesystem            Type  Size  Used Avail Use% Mounted on
notes_plat_sysinfo_459 =    /dev/mapper/data-home ext4  3.6T  1.3T  2.2T  36% /home
notes_plat_sysinfo_460 = 
notes_plat_sysinfo_461 =  ------------------------------------------------------------
notes_plat_sysinfo_462 =  22. /sys/devices/virtual/dmi/id
notes_plat_sysinfo_463 =      Vendor:         IEIT SYSTEMS
notes_plat_sysinfo_464 =      Product:        NF5280R6
notes_plat_sysinfo_465 =      Product Family: ARM
notes_plat_sysinfo_466 =      Serial:         21D103717
notes_plat_sysinfo_467 = 
notes_plat_sysinfo_468 =  ------------------------------------------------------------
notes_plat_sysinfo_469 =  23. dmidecode
notes_plat_sysinfo_470 =    Additional information from dmidecode 3.5 follows.  WARNING: Use caution when you interpret this section.
notes_plat_sysinfo_471 =    The 'dmidecode' program reads system data which is "intended to allow hardware to be accurately
notes_plat_sysinfo_472 =    determined", but the intent may not be met, as there are frequent changes to hardware, firmware, and the
notes_plat_sysinfo_473 =    "DMTF SMBIOS" standard.
notes_plat_sysinfo_474 =    Memory:
notes_plat_sysinfo_475 =      2x Samsung M393A8G40BB4-CWE 64 GB 2 rank 3200
notes_plat_sysinfo_476 = 
notes_plat_sysinfo_477 = 
notes_plat_sysinfo_478 =  ------------------------------------------------------------
notes_plat_sysinfo_479 =  24. BIOS
notes_plat_sysinfo_480 =  (This section combines info from /sys/devices and dmidecode.)
notes_plat_sysinfo_481 =     BIOS Vendor:       American Megatrends International, LLC.
notes_plat_sysinfo_482 =     BIOS Version:      05.01.29
notes_plat_sysinfo_483 =     BIOS Date:         03/19/2024
notes_plat_sysinfo_484 =     BIOS Revision:     5.15
notes_plat_sysinfo_485 =     Firmware Revision: 2.10
notes_wrap_columns = 0
notes_wrap_indent =   
num              = 505
obiwan           = 
os_exe_ext       = 
output_format    = txt,html,cfg,pdf,csv
output_root      = 
outputdir        = output
parallel_test    = 24
parallel_test_submit = 0
parallel_test_workloads = 
path             = /home/yangchunlin/cpu2017-64KB/benchspec/CPU/505.mcf_r
plain_train      = 1
platform         = 
power            = 0
power_management = 
preENV_LD_LIBRARY_PATH = %{gcc_dir}/lib64/:%{gcc_dir}/lib/:/lib64
preenv           = 0
prefix           = 
prepared_by      = root  (is never output, only tags rawfile)
ranks            = 1
rawhash_bits     = 256
rebuild          = 0
reftime          = reftime
reltol           = 
reportable       = 0
resultdir        = result
review           = 0
run              = all
runcpu           = /home/yangchunlin/cpu2017-64KB/bin/harness/runcpu --configfile ycl --size refrate --copies 24 --noreportable --tune base --iterations 1 --noreportable --nopower --runmode rate --tune base --size refrate intrate --nopreenv --note-preenv --logfile /home/yangchunlin/cpu2017-64KB/tmp/CPU2017.001/templogs/preenv.intrate.001.0.log --lognum 001.0 --from_runcpu 2
rundir           = run
runmode          = rate
safe_eval        = 1
save_build_files = 
section_specifier_fatal = 1
setprocgroup     = 1
setup_error      = 0
sigint           = 2
size             = refrate
size_class       = ref
skipabstol       = 
skipobiwan       = 
skipreltol       = 
skiptol          = 
smarttune        = base
specdiff         = specdiff
specrun          = specinvoke
srcalt           = 
srcdir           = src
srcsource        = /home/yangchunlin/cpu2017-64KB/benchspec/CPU/505.mcf_r/src
stagger          = 10
strict_rundir_verify = 1
sw_avail         = 
sw_base_ptrsize  = 64-bit
sw_compiler001   = C/C++/Fortran: Version 10.1.0 of GCC, the
sw_compiler002   = GNU Compiler Collection
sw_file          = ext4
sw_os001         = openEuler 24.03 (LTS-SP1)
sw_os002         = 6.6.0
sw_other         = 
sw_peak_ptrsize  = 64-bit
sw_state         = Run level 3 (add definition here)
sysinfo_hash_bits = 256
sysinfo_program  = specperl /home/yangchunlin/cpu2017-64KB/bin/sysinfo
sysinfo_program_hash = sysinfo:SHA:2eb381fc1a58eb8122e4a1b875c1e38b3489dac84088192aa0ec6d157b084d06
table            = 1
teeout           = 0
test_date        = Jan-2026
test_sponsor     = My Corporation
tester           = My Corporation
threads          = 1
top              = /home/yangchunlin/cpu2017-64KB
train_single_thread = 0
train_with       = train
tune             = base
uid              = 0
unbuffer         = 1
uncertainty_exception = 5
update           = 0
update_url       = http://www.spec.org/auto/cpu2017/updates/
use_submit_for_compare = 0
use_submit_for_speed = 0
username         = root
verbose          = 5
verify_binaries  = 1
version          = 1.000503
voltage_range    = 
worklist         = list
OUTPUT_RMFILES   = inp.out mcf.out
